# YourBase build configuration
# See https://docs.yourbase.io/ for reference.

dependencies:
  build:
    - go:1.17.2

build_targets:
  - name: default
    commands:
      - go test ./...

  - name: gen
    commands:
      - bash gen.sh

  - name: gen_linux
    container:
      image: yourbase/yb_ubuntu:18.04
    commands:
      - bash gen.sh
