// Code generated by 'ccgo -pkgname=lib -export-defines "" -export-enums "" -export-externs X -export-structs S -export-fields "" -export-typedefs "" -trace-translation-units -o internal/lib/treesitter_darwin_arm64.go -I upstream/tree-sitter/lib/src -I upstream/tree-sitter/lib/include upstream/tree-sitter/lib/src/get_changed_ranges.c upstream/tree-sitter/lib/src/language.c upstream/tree-sitter/lib/src/lexer.c upstream/tree-sitter/lib/src/lib.c upstream/tree-sitter/lib/src/node.c upstream/tree-sitter/lib/src/parser.c upstream/tree-sitter/lib/src/query.c upstream/tree-sitter/lib/src/stack.c upstream/tree-sitter/lib/src/subtree.c upstream/tree-sitter/lib/src/tree.c upstream/tree-sitter/lib/src/tree_cursor.c', DO NOT EDIT.

package lib

import (
	"math"
	"reflect"
	"sync/atomic"
	"unsafe"

	"modernc.org/libc"
	"modernc.org/libc/sys/types"
)

var _ = math.Pi
var _ reflect.Kind
var _ atomic.Value
var _ unsafe.Pointer
var _ types.Size_t
