// Code generated by 'ccgo -pkgname=json -export-defines  -export-enums  -export-externs X -export-structs S -export-fields  -export-typedefs  -trace-translation-units -o internal/json/json_darwin_amd64.go -I ./internal/lib -I upstream/tree-sitter/lib/include upstream/tree-sitter-json/src/parser.c', DO NOT EDIT.

package json

var CAPI = map[string]struct{}{
	"tree_sitter_json": {},
}
