// Code generated by 'ccgo -pkgname=lib -export-defines  -export-enums  -export-externs X -export-structs S -export-fields  -export-typedefs  -trace-translation-units -o internal/python/python_darwin_amd64.go -I ./internal/lib -I /var/folders/42/mlggdbg92034zjw3fl_54g_c0000gn/T/tmp.HgsdCNWs/tree-sitter/lib/include /var/folders/42/mlggdbg92034zjw3fl_54g_c0000gn/T/tmp.HgsdCNWs/tree-sitter-python/src/parser.c internal/python/scanner.c', DO NOT EDIT.

package lib

var CAPI = map[string]struct{}{
	"tree_sitter_python":                              {},
	"tree_sitter_python_external_scanner_create":      {},
	"tree_sitter_python_external_scanner_deserialize": {},
	"tree_sitter_python_external_scanner_destroy":     {},
	"tree_sitter_python_external_scanner_scan":        {},
	"tree_sitter_python_external_scanner_serialize":   {},
}
