// Code generated by 'ccgo -pkgname=python -export-defines  -export-enums  -export-externs X -export-structs S -export-fields  -export-typedefs  -trace-translation-units -o internal/python/python_darwin_amd64.go -I ./internal/lib -I upstream/tree-sitter/lib/include upstream/tree-sitter-python/src/parser.c internal/python/patch/scanner.c', DO NOT EDIT.

package python

var CAPI = map[string]struct{}{
	"tree_sitter_python":                              {},
	"tree_sitter_python_external_scanner_create":      {},
	"tree_sitter_python_external_scanner_deserialize": {},
	"tree_sitter_python_external_scanner_destroy":     {},
	"tree_sitter_python_external_scanner_scan":        {},
	"tree_sitter_python_external_scanner_serialize":   {},
}
